In [94]:
import numpy as np
import csv

In [ ]:
#Jesse Bristow
#Philani Mpofu (1848751)
#Matthew Kruger (1669326)
#Chloe Smith (1877342)

In [109]:
all_data_in = np.genfromtxt('smalldigits.csv', delimiter=',')
all_data = all_data_in[:1438]
all_data_test = all_data_in[1438:]
#unique outcomes and their count
uniqueLabels, labelCounts = np.unique(all_data[:,64],return_counts = True)
total_datapoints = np.sum(labelCounts)
print(all_data)
#print(all_data.shape)
print(all_data_test)
#print(all_data_test.shape)
print(uniqueLabels,labelCounts)
#print(np.sum(labelCounts))

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 2.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 0. 2.]]
[[0. 0. 1. ... 0. 0. 3.]
 [0. 0. 0. ... 0. 0. 4.]
 [0. 0. 1. ... 0. 0. 5.]
 ...
 [0. 0. 0. ... 0. 0. 8.]
 [0. 0. 0. ... 0. 0. 9.]
 [0. 0. 1. ... 0. 0. 8.]]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] [143 146 143 146 144 145 144 143 141 143]


Declare the main table

In [108]:
main_table = np.zeros(shape = (64,10))
#print(main_table)

Fill in the main table

In [107]:
for labelNum in range(10):
    data_for_curr_label = all_data[all_data[:,64] == labelNum]
    denominator = data_for_curr_label.shape[0]
    print(denominator)
    #For each pixel get prob of pixel being on
    for pixelInd in range(64):
        #count how many times 1 occurs in col:pixelInd from data_for_curr_label
        #print(data_for_curr_label[:,5])
        unique,counts = np.unique(data_for_curr_label[:,pixelInd] ,return_counts = True)
        
        #calculate the probability
        tempIndex = 0
        numerator = 0
        for pixelValue in unique:
            if pixelValue == 1:
                numerator = counts[tempIndex]
                break
            tempIndex = tempIndex+1
            
        main_table[pixelInd][labelNum] = float(numerator/denominator)
        

print(main_table)
print(main_table.shape)

143
146
143
146
144
145
144
143
141
143
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.01398601 0.00684932 0.         0.06206897
  0.         0.         0.         0.        ]
 [0.37762238 0.24657534 0.82517483 0.82876712 0.         0.91724138
  0.05555556 0.48251748 0.46099291 0.58741259]
 [1.         0.70547945 0.95104895 1.         0.61805556 0.99310345
  0.99305556 0.97902098 0.95744681 0.8951049 ]
 [0.95804196 0.82876712 0.82517483 0.98630137 0.95138889 0.97931034
  0.76388889 0.97902098 0.94326241 0.93706294]
 [0.29370629 0.52054795 0.23076923 0.66438356 0.20833333 0.91034483
  0.13888889 0.83916084 0.60992908 0.47552448]
 [0.         0.0890411  0.         0.03424658 0.02777778 0.4137931
  0.         0.47552448 0.         0.11888112]
 [0.         0.         0.         0.         0.01388889 0.
  0.         0.11188811 0.         0.        ]
 [0.         0.         0.         0.         0.         

Function to predict data:

In [102]:
def predict_value(data_point):
    #data_point is vector(64) with pixels
    numerator_values = np.zeros(10)
    denominator = 0.0
    for i in range(10):
        curr_total = 1.0
        for j in range(len(data_point)):
            currPixel = data_point[j]
            if currPixel == 0:
                #pixel is off
                curr_total = curr_total*(1-main_table[j][i])
            else:
                curr_total = curr_total*(main_table[j][i])
                
        numerator_values[i] = curr_total*(labelCounts[i]/total_datapoints)
        denominator = denominator + numerator_values[i]
    
    #For each label get the prob
    largestProb = -1
    largestProbLabelNum = -1
    for labelNum in range(10):
        curr_prob = numerator_values[labelNum]/denominator
        
        #print(labelNum,curr_prob)
        
        if curr_prob > largestProb:
            largestProb = curr_prob
            largestProbLabelNum = labelNum
        
    
    return largestProbLabelNum

Function to test data:

In [106]:
total_num_tests = len(all_data_test)
total_num_correct = 0
#Predict each data_point
for i in range(len(all_data_test)):
    test_dataPoint = all_data_test[i][:64]
    test_dataPointAnswer = all_data_test[i][64]
    test_predict_answer = predict_value(test_dataPoint)
    if test_dataPointAnswer == test_predict_answer:
        total_num_correct = total_num_correct + 1

accuracy = total_num_correct/total_num_tests
print(accuracy)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in double_scalars


0.8105849582172702
